# Generated by Django 5.2 on 2025-05-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_cinemahall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.movie', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Актёры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default=1, max_length=255, verbose_name='Жанры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
