# Generated by Django 5.2 on 2025-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_movie_actors_delete_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Актеры'),
        ),
    ]
