# Generated by Django 5.2 on 2025-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_movie_movie_actors_movie_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
