# Generated by Django 5.2 on 2025-05-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_movie_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='schema',
            field=models.JSONField(default=dict, verbose_name='Схема зала'),
        ),
    ]
