# Generated by Django 5.2 on 2025-05-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_cinemahall_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='schema',
        ),
    ]
