# Generated by Django 5.2 on 2025-05-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_movie_trailer_url_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie',
        ),
        migrations.CreateModel(
            name='CinemaSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=255, verbose_name='Название кинотеатра')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('metro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Метро')),
                ('showtimes', models.JSONField(verbose_name='Время сеансов')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.movie')),
            ],
            options={
                'verbose_name': 'Расписание кинотеатра',
                'verbose_name_plural': 'Расписания кинотеатров',
            },
        ),
    ]
