# Generated by Django 5.2 on 2025-05-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_cinemahall_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_time'], 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.RemoveField(
            model_name='cinemahall',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cinemahall',
            name='metro_station',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('vip', 'VIP')], default='standard', max_length=20, verbose_name='Тип места'),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.PositiveIntegerField(verbose_name='Количество рядов'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='booking.cinemahall'),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='booking.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('session', 'row', 'number')},
        ),
    ]
