# Generated by Django 5.2 on 2025-05-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_movie_cinemaschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CinemaSchedule',
        ),
    ]
