# Generated by Django 5.2 on 2025-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_delete_cinemaschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='metro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метро'),
        ),
    ]
