# Generated by Django 5.2 on 2025-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_session_options_remove_cinemahall_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='address',
            field=models.CharField(default='Адрес не указан', max_length=200, verbose_name='Адрес'),
        ),
    ]
