# Generated by Django 5.2 on 2025-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_cinemahall_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='metro_station',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Станция метро'),
        ),
    ]
